### PR TITLE
Feat/nats improvements

### PR DESCRIPTION
**Pull request by lfbrehm**
# Summary
Adds missing event messages for server to server sync, additional bug fixes and improvements.

# Changes
- Additional server only events for updating cached rules
- Missing emission of data proxy events in `user_db_handler`, `workspace_db_handler` and `service_accounts_db_handler`
- Fixed hook status in `hook_handler`
- Waiting for acknowledgement of specific proxies in `workspace_db_handler` and `hooks_handler`
- A lot of clippy suggestions

### CODE REVIEW

**Comment by lfbrehm** [comment]
I tried to address the failing tests situation. `Object::batch_create` was the culprit, but I do not know why. Maybe this is related to this [issue](https://github.com/sfackler/rust-postgres/issues/1081)

**Review by das-Abroxas — DISMISSED** [review]
Still a little too much input for a proper review but I haven't seen anything that is obviously broken.

But it's great that you've also fixed the problem with the “randomly” failing tests :raised_hands:

**Comment by lfbrehm** [comment]
I refactored the slightly ugly solution to skip the inner loops in `Object::batch_create` and `InternalRelation::batch_create`, as suggested by @St4NNi. I'm not quite happy with removing the `COPY FROM` queries, because they are suggested by the tokio_postgres [maintainer](https://github.com/sfackler/rust-postgres/issues/336#issuecomment-379560207) as a performance optimized solution.
In the long run, this should be debugged, replacing this temporary solution.

**Review by St4NNi — APPROVED** [review]
Agree with @das-Abroxas too much to properly review. We should include refactoring only changes to separate PRs in the future.

Otherwise im fine with that. LGTM!

**Pull request merged**
